name: Deploy Vulnerable Application                                  # workflow name

on:
  push:
    branches:
      - master
jobs:
  deploy-heroku:
    name: Deploy Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: 941c09ca-a7be-4ce1-85d5-aa9d978358ec
          heroku_app_name: "mtejera-vulnerableapp" #Must be unique in Heroku
          heroku_email: "mariano.garciatejera@gmail.com"
          remote_branch: "master"
          usedocker: true
